#!/usr/bin/env python3

def challenge1(movements):
    # create a var that iterates through the list finding requested position and adding the int to the var
    forward = sum([int(i[-1])for i in movements if 'forward' in i])
    down = sum([int(i[-1])for i in movements if 'down' in i])
    up = -sum([int(i[-1])for i in movements if 'up' in i])
    return forward*(down + up)


# import and convert data into a workable list
data = [i.strip() for i in open("d2_input").readlines()]
print("Challenge 1: ", challenge1(data))
